language: en
words:
  - darklua
  - Lerps
  - canvasgroup
  - eslin
  - imagelabel
  - viewportframe
  - uisizeconstraint
  - dorem
  - offwhite
  - flamework
  - rbxts
  - rbxtsc
  - isentinel
  - flamework
  - Calculator
  - pcall
  - dbaeumer
  - jiti
  - unrs
  - rokit
  - Rokit
  - rbxassetid
  - uigridlayout
  - getfenv
  - Catppuccin
  - rbxgameasset
