language: en
words:
  - darklua
  - Lerps
  - canvasgroup
  - eslin
  - imagelabel
  - viewportframe
  - uisizeconstraint
  - dorem
  - offwhite
  - flamework
  - rbxts
  - rbxtsc
  - isentinel
  - flamework
  - Calculator
  - pcall
